# SciPy:  Scientific Toolkit

# SciPy

 * SciPy is a collection of mathematical algorithms and convience functions built on Numpy data structures
 * Organized into subpackages covering different scientific computing areas
 * A data-processing and prototyping environment rivaling MATLAB

# SciPy Submodules

* Special functions (`scipy.special`) 
* Integration (`scipy.integrate`) 
* Optimization (`scipy.optimize`) 
* Interpolation (`scipy.interpolate`)
* Fourier Transforms (`scipy.fftpack`) 
* Signal Processing (`scipy.signal`)
* Linear Algebra (`scipy.linalg`)
* Sparse Eigenvalue Problems with ARPACK Compressed Sparse Graph Routines (`scipy.sparse.csgraph`)
* Statistics (`scipy.stats`)
* Multi-dimensional image processing (`scipy.ndimage`) 
* File IO (`scipy.io`)
* Weave (`scipy.weave`)
* And more. . .

# Common submodules: `scipy.integrate`

Integrate the function:

$$
f(x) = \int_{0}^4 x^2 {\rm d}x
$$

In [1]:
import scipy.integrate
ans, err = scipy.integrate.quad(lambda x: x ** 2, 0., 4)
ans

21.333333333333336

In [2]:
1 / 3. * 4 ** 3

21.333333333333332

See also: `dblquad`, `tplquad`, `fixed_quad`, `trapz`, `simps`

# Common submodules: `scipy.linalg`

### Matrix Inverse

In [3]:
import numpy as np
import scipy.linalg
a = np.random.rand(3,3)
scipy.linalg.inv(a)

array([[-2.8922658 ,  2.59892365,  0.57199444],
       [ 6.36789237,  0.74490762, -1.60447415],
       [ 1.27462131, -2.25990753,  1.16324644]])

### Eigenvalues

In [4]:
scipy.linalg.eigvals(a)

array([ 0.91883513+0.j, -0.16740995+0.j,  0.25635015+0.j])

# Common submodules: `scipy.interpolate`

### Interpolate a function

In [5]:
import numpy as np
from scipy import interpolate, integrate
x = np.arange(-1,12)
y = np.exp(-x/3.0)
f = interpolate.interp1d(x,y); f
x

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Integrate the interpolated function

In [6]:
ans, err = integrate.quad(f,0,10); ans

2.9197153790964223

### Integrate the data

In [9]:
integrate.simpson(y[1:-1], x=x[1:-1])

2.893173846607656

In [ ]:
%%javascript
function hideElements(elements, start) {
for(var i = 0, length = elements.length; i < length;i++) {
    if(i >= start) {
        elements[i].style.display = "none";
    }
}
}
var prompt_elements = document.getElementsByClassName("prompt");
hideElements(prompt_elements, 0)